name: mgm_app
description: Member-Get-Member Flutter app
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.2.0
  cloud_functions: ^5.0.3
  share_plus: ^10.0.2
  app_links: ^6.4.1
  flutter_local_notifications: ^17.2.1
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  uuid: ^4.4.0
  collection: ^1.18.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
